### ISSUE TITLE
nil pointer dereference in SetReadOnly

### ISSUE THREAD

**Issue by MOON-CLJ** [openark/orchestrator#1040]
https://github.com/openark/orchestrator/blob/17485ac9d32a70c997be21077bfe6c1544e82880/go/inst/instance_topology_dao.go#L1043

here instance maybe nil pointer，because no error handler for 

https://github.com/openark/orchestrator/blob/17485ac9d32a70c997be21077bfe6c1544e82880/go/inst/instance_topology_dao.go#L1039

cc @yangeagle

**Comment by MOON-CLJ** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8be4de]

goroutine 1382370 [running]:
github.com/github/orchestrator/go/inst.SetReadOnly(0xc000215900, 0x1, 0xc0012a3260, 0x0, 0x1)
    /tmp/build/src/orchestrator/.gopath/src/github.com/github/orchestrator/go/inst/instance_topology_dao.go:1043 +0x14e
github.com/github/orchestrator/go/logic.checkAndRecoverDeadMaster.func2(0xc000215900, 0xc00020b000)
    /tmp/build/src/orchestrator/.gopath/src/github.com/github/orchestrator/go/logic/topology_recovery.go:1067 +0x34
created by github.com/github/orchestrator/go/logic.checkAndRecoverDeadMaster
    /tmp/build/src/orchestrator/.gopath/src/github.com/github/orchestrator/go/logic/topology_recovery.go:1066 +0xa43
```

**Comment by MOON-CLJ** [comment]
@shlomi-noach It's a pleasure for give a pr to fix this
