### ISSUE TITLE
Crash in inst.moveReplicasViaGTID.func1

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#126]
Crash in orchestrator based on a version very close to v2.1.

Crash report says:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f10d5]

goroutine 1925650 [running]:
github.com/github/orchestrator/go/inst.moveReplicasViaGTID.func1.1(0xc421785aa0, 0xc42000eb80)
        /builddir/build/BUILD/orchestrator-2.0.2.29/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:610 +0x25
github.com/github/orchestrator/go/inst.moveReplicasViaGTID.func1(0xc421785aa0, 0xc42000eb80, 0xc420378580, 0xc422643730, 0xc422707600, 0xc422707620, 0xc422707640)
        /builddir/build/BUILD/orchestrator-2.0.2.29/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:630 +0xe0
created by github.com/github/orchestrator/go/inst.moveReplicasViaGTID
        /builddir/build/BUILD/orchestrator-2.0.2.29/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:630 +0x327
```

The version of go/inst/instance_topology.go is the same as in v2.0.2 (and that's almost identical except for an unrelated change to v2.1)

I'll try to look at this later but am a bit busy with other things.  Fuller anonymised logging shows:

```
2017-03-31 15:08:15 DEBUG Not elected as active node; active node: orchestrator2.dc; polling
[martini] Started GET /api/relocate-replicas/host5.dc/3306/host6.dc/3306 for 127.0.0.1:37735
2017-03-31 15:08:15 INFO Will move 7 replicas below host6.dc:3306 via GTID
2017-03-31 15:08:15 INFO Will move host2.dc:3306 below host6.dc:3306 via GTID
2017-03-31 15:08:15 INFO Will move host9.dc:3306 below host6.dc:3306 via GTID
2017-03-31 15:08:15 INFO Will move host10.dc:3306 below host6.dc:3306 via GTID
2017-03-31 15:08:15 INFO Will move host3.dc:3306 below host6.dc:3306 via GTID
2017-03-31 15:08:15 INFO Will move host8.dc:3306 below host6.dc:3306 via GTID
2017-03-31 15:08:15 INFO Will move host4.dc:3306 below host6.dc:3306 via GTID
2017-03-31 15:08:15 INFO Will move host7.dc:3306 below host6.dc:3306 via GTID
2017-03-31 15:08:15 DEBUG auditType:begin-maintenance instance:host2.dc:3306 cluster:host1.dc:3306 message:maintenanceToken: 226526, owner: orchestrator1.dc, reason: move below host6.dc:3306
2017-03-31 15:08:15 DEBUG auditType:begin-maintenance instance:host3.dc:3306 cluster:host1.dc:3306 message:maintenanceToken: 226528, owner: orchestrator1.dc, reason: move below host6.dc:3306
2017-03-31 15:08:15 DEBUG auditType:begin-maintenance instance:host10.dc:3306 cluster:host1.dc:3306 message:maintenanceToken: 226529, owner: orchestrator1.dc, reason: move below host6.dc:3306
2017-03-31 15:08:15 DEBUG auditType:begin-maintenance instance:host8.dc:3306 cluster:host1.dc:3306 message:maintenanceToken: 226530, owner: orchestrator1.dc, reason: move below host6.dc:3306
2017-03-31 15:08:15 DEBUG auditType:begin-maintenance instance:host9.dc:3306 cluster:host1.dc:3306 message:maintenanceToken: 226527, owner: orchestrator1.dc, reason: move below host6.dc:3306
2017-03-31 15:08:15 DEBUG auditType:begin-maintenance instance:host7.dc:3306 cluster:host1.dc:3306 message:maintenanceToken: 226531, owner: orchestrator1.dc, reason: move below host6.dc:3306
2017-03-31 15:08:15 DEBUG auditType:begin-maintenance instance:host4.dc:3306 cluster:host1.dc:3306 message:maintenanceToken: 226532, owner: orchestrator1.dc, reason: move below host6.dc:3306
2017-03-31 15:08:15 ERROR ReadTopologyInstance(host2.dc:3306) show variables like 'maxscale%': Error 3159: Connections using insecure transport are prohibited while --require_secure_transport=ON.
2017-03-31 15:08:15 ERROR ReadTopologyInstance(host2.dc:3306) show variables like 'maxscale%': Error 3159: Connections using insecure transport are prohibited while --require_secure_transport=ON.
2017-03-31 15:08:15 DEBUG auditType:end-maintenance instance:host2.dc:3306 cluster:host1.dc:3306 message:maintenanceToken: 226526
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f10d5]

goroutine 1925650 [running]:
github.com/github/orchestrator/go/inst.moveReplicasViaGTID.func1.1(0xc421785aa0, 0xc42000eb80)
        /builddir/build/BUILD/orchestrator-2.0.2.29/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:610 +0x25
github.com/github/orchestrator/go/inst.moveReplicasViaGTID.func1(0xc421785aa0, 0xc42000eb80, 0xc420378580, 0xc422643730, 0xc422707600, 0xc422707620, 0xc422707640)
        /builddir/build/BUILD/orchestrator-2.0.2.29/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:630 +0xe0
created by github.com/github/orchestrator/go/inst.moveReplicasViaGTID
        /builddir/build/BUILD/orchestrator-2.0.2.29/GO/src/github.com/github/orchestrator/go/inst/instance_topology.go:630 +0x327
```

I am enforcing TLS on some boxes which currently prevents orchestrator reaching them. Maybe there's something related here but I am not sure.

For now just making the issue visible.

**Comment by shlomi-noach** [comment]
Thank you. Seems like `golang` is not very helpful in identifying the line within an anonymous function.

**Comment by sjmudd** [comment]
Closing as looks like fixed in: https://github.com/github/orchestrator/issues/263
