### ISSUE TITLE
Orchestrator didn't register a detection for an outage; discovery saw i/o timeouts

### ISSUE THREAD

**Issue by erikhalperin** [openark/orchestrator#1438]
### Summary
Hi, we had a situation where a mysql master instance became impaired when the disk filled up, but orchestrator didn't register a detection of the outage (I would have expected an UnreachableMaster even if recovery wasn't possible). The logs show that discovery of the instance started to fail with `i/o timeout` errors but nothing else interesting. Unfortunately we had neither debug logging nor stack tracing enabled. We're on version 3.1.1.
```
2022-03-09T10:23:14.651305399Z [mysql] 2022/03/09 10:23:14 packets.go:36: read tcp 172.16.167.156:21476->172.16.112.22:3306: i/o timeout
2022-03-09T10:23:14.65132807Z 2022-03-09 10:23:14 ERROR invalid connection
```
### Details
A few hours before the outage that wasn't detected, there was a previous outage where the disk filled up on the original master. Orch detected that as a DeadMaster and failed over to another instance (`172.16.112.22`). So the original instance (now a replica) was also impaired at the time of the second outage. At 10:23 the disk for `172.16.112.22` filled up, but no detection was registered. Eventually we were alerted and someone resolved the disk issue manually. We noticed after the fact that the process list for the impaired master slowly filled up during the outage, likely due to hanging `show master status` queries, but it never hit max_connections.
[1 minute snippet of logs from 10:23 - 10:24](https://gist.github.com/erikhalperin/01cb0434e1d8444118873ceb8afb4c1d)

- [orchestrator.conf.json](https://gist.github.com/erikhalperin/6f3885c93033b78809cb79df9e6c20fb)
- Topology - the IPs here are out of date, the topology at the time would look like (all running mysql 5.7.25-28):
```
172.16.153.32 -> good slave
172.16.173.60 -> impaired slave
172.16.112.22 -> master
```

```
$ /usr/local/orchestrator/resources/bin/orchestrator-client -c topology -alias Minilla.0
172.16.125.111:3306   [0s,ok,5.7.25-28-log,rw,ROW,>>,GTID]
+ 172.16.110.164:3306 [26005s,lag,5.7.25-28-log,ro,ROW,>>,GTID]
- 172.16.126.0:3306   [unknown,invalid,5.7.36-39-log,ro,ROW,>>,GTID]
+ 172.16.130.138:3306 [0s,ok,5.7.25-28-log,ro,ROW,>>,GTID]
+ 172.16.133.53:3306  [0s,ok,5.7.25-28-log,ro,ROW,>>,GTID]
+ 172.16.148.27:3306  [0s,ok,5.7.36-39-log,ro,ROW,>>,GTID]
+ 172.16.183.75:3306  [0s,ok,5.7.25-28-log,ro,ROW,>>,GTID]
```

I tried to reproduce this with debug logging and stack tracing enabled and was able to reproduce the i/o timeouts (which appear to be coming from `show master status` queries hanging on the impaired master) but orchestrator did register an UnreachableMaster. 
[Full logs](https://gist.github.com/erikhalperin/d2da8c5160342cf149a60ba0af0c2e8e)
```
[mysql] 2022/03/28 17:17:51 packets.go:36: read tcp 172.18.143.7:31582->172.18.177.66:3306: i/o timeout
2022-03-28 17:17:51 ERROR invalid connection
goroutine 29046183 [running]:
runtime/debug.Stack(0x2c, 0x2800, 0xc000b6a5c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/orchestrator/vendor/github.com/openark/golib/log.logErrorEntry(0x2, 0xd11c60, 0xc000058830, 0xbf8c00, 0x12)
	/usr/share/hubspot/build/workspace/vitess-internal/docker-images/orchestrator/orchestrator/.gopath/src/github.com/github/orchestrator/vendor/github.com/openark/golib/log/log.go:178 +0xe7
github.com/github/orchestrator/vendor/github.com/openark/golib/log.Errore(...)
	/usr/share/hubspot/build/workspace/vitess-internal/docker-images/orchestrator/orchestrator/.gopath/src/github.com/github/orchestrator/vendor/github.com/openark/golib/log/log.go:224
github.com/github/orchestrator/vendor/github.com/openark/golib/sqlutils.QueryRowsMap(0xc000a3a3c0, 0xbf8c83, 0x12, 0xc000271fa0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/share/hubspot/build/workspace/vitess-internal/docker-images/orchestrator/orchestrator/.gopath/src/github.com/github/orchestrator/vendor/github.com/openark/golib/sqlutils/sqlutils.go:256 +0x196
github.com/github/orchestrator/go/inst.ReadTopologyInstanceBufferable.func4(0xc000807bd0, 0xc000a3a3c0, 0xc000b90700, 0xc0004a8d50)
	/usr/share/hubspot/build/workspace/vitess-internal/docker-images/orchestrator/orchestrator/.gopath/src/github.com/github/orchestrator/go/inst/instance_dao.go:405 +0xd1
created by github.com/github/orchestrator/go/inst.ReadTopologyInstanceBufferable
	/usr/share/hubspot/build/workspace/vitess-internal/docker-images/orchestrator/orchestrator/.gopath/src/github.com/github/orchestrator/go/inst/instance_dao.go:403 +0x2a70
2022-03-28 17:17:51 DEBUG writeInstance: will not update database_instance due to error: invalid connection
```

**Comment by makmanalp** [comment]
Interestingly the error happens in `ReadTopologyInstanceBufferable` and `DiscoverInstance` notes that a panic can happen within that: 

https://github.com/openark/orchestrator/blob/c72a6c89bb4cd18d43d3c6e5529502e0a2472290/go/logic/orchestrator.go#L233-L236

And that works because the panic should be caught and recovered here, returning nil:

https://github.com/openark/orchestrator/blob/c72a6c89bb4cd18d43d3c6e5529502e0a2472290/go/inst/instance_dao.go#L279-L284

which results in incrementing the failed discovery counter:

https://github.com/openark/orchestrator/blob/c72a6c89bb4cd18d43d3c6e5529502e0a2472290/go/logic/orchestrator.go#L241-L250

but then I can't find anything being done with that counter

**Comment by makmanalp** [comment]
Old case of disk filling up https://github.com/openark/orchestrator/issues/698 (though in that case it seems like there were  different / no obvious direct symptoms, so probably unhelpful to us)
