### ISSUE TITLE
Discovery crashes when on different port

### ISSUE THREAD

**Issue by djuntgen** [openark/orchestrator#324]
# Crash when running discover on port 3307

When discovery on port 3307, orchestrator crashes with memory nil pointer

![image](https://user-images.githubusercontent.com/2113969/31896602-310cea04-b7e2-11e7-9643-b9fba77baf8e.png)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x962c87]

goroutine 1 [running]:
github.com/github/orchestrator/go/app.Cli(0x7ffd025eb8e3, 0x8, 0x0, 0x7ffd025eb8ef, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/shlomi-noach/dev/go/src/github.com/github/orchestrator/go/app/cli.go:1262 +0xe787
github.com/github/orchestrator/go/app.CliWrapper(0x7ffd025eb8e3, 0x8, 0x0, 0x7ffd025eb8ef, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/shlomi-noach/dev/go/src/github.com/github/orchestrator/go/app/cli.go:149 +0x23e
main.main()
        /home/shlomi-noach/dev/go/src/github.com/github/orchestrator/go/cmd/orchestrator/main.go:162 +0xe4f
```

## Version
```
[root@dba /var/log]# orchestrator --version
3.0.2
992507c56e99fedb4660968c8a293e9a6b290df0
```

**Comment by shlomi-noach** [comment]
that's unexpected, of course. Line at fault: https://github.com/github/orchestrator/blob/v3.0.2/go/app/cli.go#L1262
Will look into it.

**Comment by shlomi-noach** [comment]
I'm just wondering, since this issue is titled "...when on different port" -- does it not crash for you when you're discovering on port `3306`?

I'm unable to reproduce this. It seems like this would happen when `ReadTopologyInstance` would return `nil` for `instance` and `nil` for `error`, which doesn't make sense.

Is there an actual server at this host:3307?

**Comment by djuntgen** [comment]
@shlomi-noach - yes, only when using a port other than the default and yes, there is a server on the host at port 3307

**Comment by shlomi-noach** [comment]
https://github.com/github/orchestrator/pull/325 will mitigate by producing an error if instance is not discoverable -- but I still can't figure out why this happened to you.
FWIW, I'm running and testing on non-`3306` ever since `orchestrator` was created, so using non-standard ports is nothing new. I'm unable to reproduce locally.

@djuntgen any hint on your side as for what other difference there is would be helpful. Different kind of proxy on `3307`? Different firewall rules? Privileges?

**Comment by djuntgen** [comment]
@shlomi-noach - Yes - I found the issue:

Add the following to your `.json` config, the error will occur.
```
{
   "HostnameResolveMethod": "default"
   "MySQLHostnameResolveMethod": "@@report_host"
}
```

By removing *both* lines the discovery works.

**Comment by shlomi-noach** [comment]
> "MySQLHostnameResolveMethod": "@@report_host"

Do you have `report_host` configured on your box in the first place?
I prefer using

```json
{
   "HostnameResolveMethod": "default",
   "MySQLHostnameResolveMethod": "@@hostname"
}
```

**Comment by djuntgen** [comment]
Apparently, I do not for the server running on port 3307. The reason for using @@report_host is that I am monitoring mysql servers that are within a third party data Center NAT'ed over VPN. The hostname of the machines is meaningless, VMs with random hostnames. Also, the local @@hostname is not resolvable from the Orchestrator service running on my server, DNS is not configured to reach over the VPN. 

Is there a way to use @@report_host for an aliased cluster only? Also - a better fix would be to do a waterfall approach, if @@report_host fails, fall down to @@localhost.

Suggestion:
```
   "MySQLHostnameResolveMethod": ["@@report_host", "@@hostname"]
```

**Comment by shlomi-noach** [comment]
> Is there a way to use @@report_host for an aliased cluster only?

There is no such way at this time.

A waterfall approach is possible. For backwards compatibility it would have to be a different variable. This would lead to some confusion, though, I suspect.

But, if hostnames are meaningless, I'd suggest:

```json
{
   "HostnameResolveMethod": "none",
   "MySQLHostnameResolveMethod": ""
}
```

**Comment by shlomi-noach** [comment]
Premature "Enter". The above would instruct `orchestrator` to not resolve at all.

You would need to use IPs all over the place. That is, you'll need to configure all your replicas like so: `change master to master_host='123.45.6.78'`.
