### ISSUE TITLE
`suggest-promoted-replacement` crashes on Ubuntu 14.04

### ISSUE THREAD

**Issue by stankevich** [openark/orchestrator#381]
```
$ lsb_release -d
Description:	Ubuntu 14.04.5 LTS
```

```
$ orchestrator -c suggest-promoted-replacement -i <cluster>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85d147]

goroutine 1 [running]:
github.com/github/orchestrator/go/inst.ReadInstance(0x0, 0xc4201c3298, 0x1dcefca2, 0xb898438262f923a9, 0xc400000001)
	/home/shlomi-noach/go/src/github.com/github/orchestrator/go/inst/instance_dao.go:1032 +0x47
github.com/github/orchestrator/go/app.validateInstanceIsFound(0x0, 0x1c)
	/home/shlomi-noach/go/src/github.com/github/orchestrator/go/app/cli.go:122 +0x2f
github.com/github/orchestrator/go/app.Cli(0x7ffc25a076a2, 0x1c, 0x0, 0xc420198c50, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/shlomi-noach/go/src/github.com/github/orchestrator/go/app/cli.go:1398 +0xbb9b
github.com/github/orchestrator/go/app.CliWrapper(0x7ffc25a076a2, 0x1c, 0x0, 0x7ffc25a076c2, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/shlomi-noach/go/src/github.com/github/orchestrator/go/app/cli.go:149 +0x20d
main.main()
	/home/shlomi-noach/go/src/github.com/github/orchestrator/go/cmd/orchestrator/main.go:158 +0xdb9
```

**Comment by shlomi-noach** [comment]
`orchestrator -version`?

**Comment by stankevich** [comment]
```
$ orchestrator -version
3.0.5
fbfc0465c0ce44f80942ead81f1dc1ba38980b89
```

**Comment by shlomi-noach** [comment]
Does this reproduce? Can you please print out the topology? `orchestrator -c topology -i <cluster>`

**Comment by stankevich** [comment]
Happens every time I run the command. Never had it run successfully.

```
$ orchestrator -c topology -i data
data:3306    [0s,ok,5.7.19-17-log,rw,ROW,>>,GTID]
+ data2:3306 [0s,ok,5.7.19-17-log,ro,ROW,>>,GTID]
+ data3:3306 [0s,ok,5.7.19-17-log,ro,ROW,>>,GTID]
+ data4:3306 [0s,ok,5.7.19-17-log,ro,ROW,>>,GTID]
```

**Comment by shlomi-noach** [comment]
Thank you -- reproduced! Looking into.

**Comment by shlomi-noach** [comment]
Interestingly `suggest-promoted-replacement` is tested in CI and passes all tests (also on my local box). Need to figure out what's different about this case.

**Comment by shlomi-noach** [comment]
Ha, OK. I confess this got me confused. And my answer isn't that pretty. TL;DR: you shouldn't be using this command and it was only exposed for the benefit of integration tests. I should probably have called it `-c internal-only-suggest-promoted-replacement` and should have documented is as much.

- The command checks whether, in a scenario where you have a master (`-i`) AND a server you wish to promote (`-d`), `orchestrator` is able to find an even better server that can be promoted on top of `-d` before completing the failover.
- You must pass both `-i` and `-d`
- `orchestrator` should have verified that instead of bailing out on null pointer exception
- You shouldn't use the command.

**Comment by stankevich** [comment]
Gotcha, thanks for explaining!

**Comment by stankevich** [comment]
Closing. Feel free to reopen if you're planning to rename the command and/or add args verification.

**Comment by djuntgen** [comment]
Hi all - I was curious about this command as well `suggest-promoted-replacement` and ran into a crash on CentOS 6

```
orchestrator -c suggest-promoted-replacement
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86beb7]

goroutine 1 [running]:
github.com/github/orchestrator/go/inst.ReadInstance(0x0, 0x1a46e9f8, 0xdbce0e88e6ac2248, 0x1800, 0xdb0000c42011e800)
        /root/dev/go/src/github.com/github/orchestrator/go/inst/instance_dao.go:1032 +0x47
github.com/github/orchestrator/go/app.validateInstanceIsFound(0x0, 0x1c)
        /root/dev/go/src/github.com/github/orchestrator/go/app/cli.go:122 +0x2f
github.com/github/orchestrator/go/app.Cli(0x7ffd74bca8e1, 0x1c, 0x0, 0xb5c900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/dev/go/src/github.com/github/orchestrator/go/app/cli.go:1398 +0xbc87
github.com/github/orchestrator/go/app.CliWrapper(0x7ffd74bca8e1, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/dev/go/src/github.com/github/orchestrator/go/app/cli.go:149 +0x23e
main.main()
        /root/dev/go/src/github.com/github/orchestrator/go/cmd/orchestrator/main.go:158 +0xe32
[xxx@dba ~]$ orchestrator --version
3.0.5
fbfc0465c0ce44f80942ead81f1dc1ba38980b89

[xxx@dba ~]$ cat /etc/redhat-release
CentOS release 6.9 (Final)

[xxx@dba ~]$ uname -a
Linux dba.xxx.com 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks!

**Comment by shlomi-noach** [comment]
@djuntgen hopefully my explanation above should satisfy your question?
