### ISSUE TITLE
Unable to promote slave

### ISSUE THREAD

**Issue by ManjotS** [openark/orchestrator#421]
When promoting a slave  with 3.0.6 we get:
```
[martini] Started GET /orchestrator/api/make-co-master/bc-db-integration-01/3306 for 127.0.0.1:42230
[mysql] 2018/02/27 21:37:10 packets.go:36: unexpected EOF
2018-02-27 21:37:10 ERROR invalid connection
2018-02-27 21:37:10 ERROR invalid connection
2018-02-27 21:37:10 ERROR invalid connection
[martini] Completed 500 Internal Server Error in 34.669359ms
```
Sometimes we are able to get past this error (manually doing change master to etc) and then when trying to fail back or do any operation we get:

```
2018-02-27 23:48:38 INFO starting orchestrator, version: 3.0.6, git commit: a77ee001dc95b8dc0476b929164f37b1141f54c1
2018-02-27 23:48:38 INFO Read config: /etc/orchestrator.conf.json
2018-02-27 23:48:38 DEBUG Hostname unresolved yet: bc-db-integration-01
2018-02-27 23:48:38 DEBUG Cache hostname resolve bc-db-integration-01 as bc-db-integration-01
2018-02-27 23:48:38 DEBUG Connected to orchestrator backend: orchestrator:?@tcp(127.0.0.1:3306)/orchestrator?timeout=1s
2018-02-27 23:48:38 DEBUG Orchestrator pool SetMaxOpenConns: 128
2018-02-27 23:48:38 DEBUG Initializing orchestrator
2018-02-27 23:48:38 INFO Connecting to backend: maxConnections: 128, maxIdleConns: 32
2018-02-27 23:48:38 DEBUG Hostname unresolved yet: bc-db-integration
2018-02-27 23:48:38 DEBUG Cache hostname resolve bc-db-integration as bc-db-integration
2018-02-27 23:48:38 DEBUG Hostname unresolved yet: bc-db-integration
2018-02-27 23:48:38 DEBUG Cache hostname resolve bc-db-integration as bc-db-integration
2018-02-27 23:48:38 INFO Will detach bc-db-integration-01:3306
2018-02-27 23:48:38 INFO auditType:begin-maintenance instance:bc-db-integration-01:3306 cluster:bc-db-integration:3306 message:maintenanceToken: 33, owner: root, reason: detach replica
2018-02-27 23:48:38 INFO Stopped slave on bc-db-integration-01:3306, Self:binlog.000002:679, Exec:binlog.000001:924
2018-02-27 23:48:38 ERROR Error 1776: Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active.
2018-02-27 23:48:38 ERROR Error 1776: Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active.
2018-02-27 23:48:38 INFO Started slave on bc-db-integration-01:3306
2018-02-27 23:48:38 ERROR Error 1776: Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active.
2018-02-27 23:48:38 INFO auditType:end-maintenance instance:bc-db-integration-01:3306 cluster:bc-db-integration:3306 message:maintenanceToken: 33
2018-02-27 23:48:38 FATAL Error 1776: Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active.
```
We looked at some previous tickets and changed grants as well:

```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for orchestrator@10.20.0.32                                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT RELOAD, PROCESS, SUPER, REPLICATION SLAVE ON *.* TO 'orchestrator'@'10.20.0.32' IDENTIFIED BY PASSWORD '....' |
| GRANT ALL PRIVILEGES ON `mysql`.`slave_master_info` TO 'orchestrator'@'10.20.0.32'                                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
```

cc @PsyonixEvan

**Comment by shlomi-noach** [comment]
Hi @ManjotS , I'm missing some info here:

- What is the topology? Can you dump a `orchestrator -c topology` please?
- In particular, is this a GTID-enabled topology? (I will find that out from the output above)
- The `unexpected EOF` and `invalid connection` are generated by the underlying go-MySQL driver. I'm wondering whether there's any connectivity issues from `orchestrator` to the servers? Firewall? 
- Is SSL enabled?
 
> Sometimes we are able to get past this error (manually doing change master to etc) and then when trying to fail back or do any operation we get:

I'm really lost about this because I don't understand the context.

> and then when trying to fail back or do any operation we get:

Can you please specify exactly what it is you're trying to do? What command you're running? Otherwise I can't really know what's wrong.

**Comment by ManjotS** [comment]
Hi @shlomi-noach 

- Topology is single master slave, freshly built (I don't have access currently)
- It is GTID Enabled
- This is all internal Google cloud ips, other tools such as proxysql etc are not having any network issues, we used telnet to troubleshoot as well and there were no network issues.
- SSL is not enabled.

We tried make-co-master, graceful and forceful master takeover, same errors as above.

**Comment by PsyonixEvan** [comment]
Hi @shlomi-noach 

Here's the output from orchestrator -c topology:

```
bc-db-integration:3306      [0s,ok,5.6.39-83.1-log,rw,ROW,>>,GTID]
+ bc-db-integration-01:3306 [0s,ok,5.6.39-83.1-log,ro,ROW,>>,GTID]
```

**Comment by shlomi-noach** [comment]
Thank you. Still no obvious insight. Can you please re-run `orchestrator --debug --stack http`, perhaps `--stack` can give us more info.

**Comment by PsyonixEvan** [comment]
Sorry for the deplay, here's the output for orchestrator --debug --stack http:

```
2018-03-05 23:18:04 INFO starting orchestrator, version: 3.0.6, git commit: a77ee001dc95b8dc0476b929164f37b1141f54c1
2018-03-05 23:18:04 INFO Read config: /etc/orchestrator.conf.json
2018-03-05 23:18:04 DEBUG Connected to orchestrator backend: orchestrator:?@tcp(127.0.0.1:3306)/orchestrator?timeout=1s
2018-03-05 23:18:04 DEBUG Orchestrator pool SetMaxOpenConns: 128
2018-03-05 23:18:04 DEBUG Initializing orchestrator
2018-03-05 23:18:04 INFO Connecting to backend: maxConnections: 128, maxIdleConns: 32
2018-03-05 23:18:04 INFO Starting Discovery
2018-03-05 23:18:04 INFO Registering endpoints
2018-03-05 23:18:04 INFO continuous discovery: setting up
2018-03-05 23:18:04 INFO continuous discovery: starting
2018-03-05 23:18:04 DEBUG Queue.startMonitoring(DEFAULT)
2018-03-05 23:18:04 INFO Starting HTTP listener on :4000
2018-03-05 23:18:04 FATAL listen tcp :4000: bind: address already in use
goroutine 1 [running]:
runtime/debug.Stack(0x48, 0x80, 0xc420720360)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/orchestrator/vendor/github.com/openark/golib/log.logErrorEntry(0x0, 0x10dd3c0, 0xc4200806e0, 0xc4200806e0, 0xc4200885b0)
        /home/shlomi-noach/go/src/github.com/github/orchestrator/vendor/github.com/openark/golib/log/log.go:178 +0xfd
github.com/github/orchestrator/vendor/github.com/openark/golib/log.Fatale(0x10dd3c0, 0xc4200806e0, 0x10dcd80, 0xc420268100)
        /home/shlomi-noach/go/src/github.com/github/orchestrator/vendor/github.com/openark/golib/log/log.go:255 +0x3e
github.com/github/orchestrator/go/app.standardHttp(0xb50101)
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/app/http.go:165 +0x6af
github.com/github/orchestrator/go/app.Http(0xc420198201)
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/app/http.go:56 +0x93
main.main()
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/cmd/orchestrator/main.go:160 +0xeae
```

**Comment by shlomi-noach** [comment]
This log indicates you are running another orchestrator instance in the box, and is irrelevant to the problem described.

**Comment by rbroemeling** [comment]
@shlomi-noach I've tried orchestrator on two clusters now -- the first one didn't exhibit this problem, but now on the second cluster where I'm using it I see exactly this issue. During a graceful fail-over, the "old" master doesn't re-enter the cluster due to errors around "Error 1776: Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active."

This is with Orchestrator 3.0.10 (the cluster where this DID NOT occur was on Orchestrator 3.0.9, though I don't think that it is compelling to say that this was caused by the minor version bump).

Interestingly, even though the cluster of servers is fully GTID on Percona Server (5.6.39-83.1-1.stretch if that helps), Orchestrator reports that it is attempting to fail-over with PseudoGTID (does this have to do with `GTIDMode` being detected as ""?):

```
Error 1776: Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active.
{
  "Id": 5,
  "UID": "1526588778832796425:306df9b13b414653e36481762969236785479dc480f07c18b70bd2710e7d7050",
  "AnalysisEntry": {
    "AnalyzedInstanceKey": {
      "Hostname": "database-server-a",
      "Port": 3306
    },
    "AnalyzedInstanceMasterKey": {
      "Hostname": "",
      "Port": 0
    },
    "ClusterDetails": {
      "ClusterName": "database-server-a:3306",
      "ClusterAlias": "database-server",
      "ClusterDomain": "",
      "CountInstances": 3,
      "HeuristicLag": 0,
      "HasAutomatedMasterRecovery": false,
      "HasAutomatedIntermediateMasterRecovery": false
    },
    "AnalyzedInstanceDataCenter": "",
    "AnalyzedInstancePhysicalEnvironment": "",
    "IsMaster": false,
    "IsCoMaster": false,
    "LastCheckValid": false,
    "LastCheckPartialSuccess": false,
    "CountReplicas": 0,
    "CountValidReplicas": 0,
    "CountValidReplicatingReplicas": 0,
    "CountReplicasFailingToConnectToMaster": 0,
    "CountStaleReplicas": 0,
    "CountDowntimedReplicas": 0,
    "ReplicationDepth": 0,
    "SlaveHosts": [],
    "IsFailingToConnectToMaster": false,
    "Analysis": "DeadMaster",
    "Description": "",
    "StructureAnalysis": null,
    "IsDowntimed": false,
    "IsReplicasDowntimed": false,
    "DowntimeEndTimestamp": "",
    "DowntimeRemainingSeconds": 0,
    "IsBinlogServer": false,
    "PseudoGTIDImmediateTopology": false,
    "OracleGTIDImmediateTopology": false,
    "MariaDBGTIDImmediateTopology": false,
    "BinlogServerImmediateTopology": false,
    "CountStatementBasedLoggingReplicas": 0,
    "CountMixedBasedLoggingReplicas": 0,
    "CountRowBasedLoggingReplicas": 0,
    "CountDistinctMajorVersionsLoggingReplicas": 0,
    "IsActionableRecovery": true,
    "ProcessingNodeHostname": "",
    "ProcessingNodeToken": "",
    "CountAdditionalAgreeingNodes": 0,
    "StartActivePeriod": "",
    "SkippableDueToDowntime": false,
    "GTIDMode": "",
    "MinReplicaGTIDMode": "",
    "MaxReplicaGTIDMode": "",
    "CommandHint": "graceful-master-takeover"
  },
  "SuccessorKey": {
    "Hostname": "database-server-b",
    "Port": 3306
  },
  "SuccessorAlias": "",
  "IsActive": false,
  "IsSuccessful": true,
  "LostReplicas": [],
  "ParticipatingInstanceKeys": [],
  "AllErrors": [
    "PseudoGTIDPattern not configured; cannot use Pseudo-GTID"
  ],
  "RecoveryStartTimestamp": "",
  "RecoveryEndTimestamp": "",
  "ProcessingNodeHostname": "",
  "ProcessingNodeToken": "",
  "Acknowledged": false,
  "AcknowledgedAt": "",
  "AcknowledgedBy": "",
  "AcknowledgedComment": "",
  "LastDetectionId": 0,
  "RelatedRecoveryId": 0,
  "RecoveryType": "MasterRecoveryPseudoGTID"
}
```

Note that according to the `topology` command, though, GTID is enabled (note: this was done AFTER I re-added the "missing" server to the topology manually, which is why it is "back"):

```$ orchestrator-client -c topology -i database-server-a
database-server-b:3306   [0s,ok,5.6.39-83.1-log,rw,MIXED,>>,GTID]
+ database-server-a:3306 [0s,ok,5.6.39-83.1-log,ro,MIXED,>>,GTID]
+ database-server-c:3306 [0s,ok,5.6.39-83.1-log,ro,MIXED,>>,GTID]
```

**Comment by rbroemeling** [comment]
GTID variables from each host are as follows

Server A:
```
ysql> SHOW VARIABLES LIKE 'gtid_%';
+----------------------+-----------+
| Variable_name        | Value     |
+----------------------+-----------+
| gtid_deployment_step | OFF       |
| gtid_executed        |           |
| gtid_mode            | ON        |
| gtid_next            | AUTOMATIC |
| gtid_owned           |           |
| gtid_purged          |           |
+----------------------+-----------+
6 rows in set (0.00 sec)
```

Server B:
```
mysql> SHOW VARIABLES LIKE 'gtid_%';
+----------------------+-------------------------------------------+
| Variable_name        | Value                                     |
+----------------------+-------------------------------------------+
| gtid_deployment_step | OFF                                       |
| gtid_executed        |                                           |
| gtid_mode            | ON                                        |
| gtid_next            | AUTOMATIC                                 |
| gtid_owned           |                                           |
| gtid_purged          | 12b8e640-3ec1-11e8-b6bb-1866daf1b5d8:1-21 |
+----------------------+-------------------------------------------+
6 rows in set (0.00 sec)
```

Server C:
```
mysql> SHOW VARIABLES LIKE 'gtid_%';
+----------------------+-------------------------------------------+
| Variable_name        | Value                                     |
+----------------------+-------------------------------------------+
| gtid_deployment_step | OFF                                       |
| gtid_executed        |                                           |
| gtid_mode            | ON                                        |
| gtid_next            | AUTOMATIC                                 |
| gtid_owned           |                                           |
| gtid_purged          | 12b8e640-3ec1-11e8-b6bb-1866daf1b5d8:1-21 |
+----------------------+-------------------------------------------+
6 rows in set (0.00 sec)
```

`gtid_purged` is different on B and C because they were slaved to A after initialization ("12b8e640-3ec1-11e8-b6bb-1866daf1b5d8" is Server A).

**Comment by shlomi-noach** [comment]
> does this have to do with GTIDMode being detected as ""?

Quite likely. Can you please:

```
SELECT @@global.version
```

on all boxes, and:

```
curl http://your-orchestrator/api/instance/database-server-a/3306
```
?

**Comment by rbroemeling** [comment]
Sure thing, @shlomi-noach -- anything that I can do to help. Please see the requested information below:

```
[database-server-a:~]$ mysql --execute 'SELECT @@global.version';
+------------------+
| @@global.version |
+------------------+
| 5.6.39-83.1-log  |
+------------------+

[database-server-b:~]$ mysql --execute 'SELECT @@global.version';
+------------------+
| @@global.version |
+------------------+
| 5.6.39-83.1-log  |
+------------------+

[database-server-c:~]$ mysql --execute 'SELECT @@global.version';
+------------------+
| @@global.version |
+------------------+
| 5.6.39-83.1-log  |
+------------------+
```

```
$ curl "${ORCHESTRATOR_API}/instance/database-server-a/3306"
{
  "Key": {
    "Hostname": "database-server-a",
    "Port": 3306
  },
  "InstanceAlias": "",
  "Uptime": 461827,
  "ServerID": 81,
  "ServerUUID": "12b8e640-3ec1-11e8-b6bb-1866daf1b5d8",
  "Version": "5.6.39-83.1-log",
  "VersionComment": "Percona Server (GPL), Release 83.1, Revision da5a1c2923f",
  "FlavorName": "Percona",
  "ReadOnly": false,
  "Binlog_format": "MIXED",
  "BinlogRowImage": "FULL",
  "LogBinEnabled": true,
  "LogSlaveUpdatesEnabled": true,
  "SelfBinlogCoordinates": {
    "LogFile": "database-server-a-81-bin-log.000046",
    "LogPos": 24181841,
    "Type": 0
  },
  "MasterKey": {
    "Hostname": "",
    "Port": 0
  },
  "IsDetachedMaster": false,
  "Slave_SQL_Running": false,
  "Slave_IO_Running": false,
  "HasReplicationFilters": false,
  "GTIDMode": "ON",
  "SupportsOracleGTID": true,
  "UsingOracleGTID": false,
  "UsingMariaDBGTID": false,
  "UsingPseudoGTID": false,
  "ReadBinlogCoordinates": {
    "LogFile": "",
    "LogPos": 0,
    "Type": 0
  },
  "ExecBinlogCoordinates": {
    "LogFile": "",
    "LogPos": 0,
    "Type": 0
  },
  "IsDetached": false,
  "RelaylogCoordinates": {
    "LogFile": "",
    "LogPos": 0,
    "Type": 1
  },
  "LastSQLError": "",
  "LastIOError": "",
  "SecondsBehindMaster": {
    "Int64": 0,
    "Valid": false
  },
  "SQLDelay": 0,
  "ExecutedGtidSet": "",
  "GtidPurged": "",
  "SlaveLagSeconds": {
    "Int64": 0,
    "Valid": false
  },
  "SlaveHosts": [
    {
      "Hostname": "database-server-c",
      "Port": 3306
    }
  ],
  "ClusterName": "database-server-a:3306",
  "SuggestedClusterAlias": "database-server",
  "DataCenter": "",
  "PhysicalEnvironment": "",
  "ReplicationDepth": 0,
  "IsCoMaster": false,
  "HasReplicationCredentials": false,
  "ReplicationCredentialsAvailable": false,
  "SemiSyncEnforced": false,
  "SemiSyncMasterEnabled": false,
  "SemiSyncReplicaEnabled": false,
  "LastSeenTimestamp": "2018-05-22T14:25:24Z",
  "IsLastCheckValid": true,
  "IsUpToDate": true,
  "IsRecentlyChecked": true,
  "SecondsSinceLastSeen": {
    "Int64": 5,
    "Valid": true
  },
  "CountMySQLSnapshots": 0,
  "IsCandidate": false,
  "PromotionRule": "neutral",
  "IsDowntimed": false,
  "DowntimeReason": "",
  "DowntimeOwner": "",
  "DowntimeEndTimestamp": "",
  "ElapsedDowntime": 0,
  "UnresolvedHostname": "",
  "AllowTLS": false,
  "LastDiscoveryLatency": 2931951
}
```

Interestingly, `GTIDMode` is no longer "" on this box. I wonder when that changed?

**Comment by shlomi-noach** [comment]
Could you please re-test with [3.0.11](https://github.com/github/orchestrator/releases/tag/v3.0.11)? It has a couple fixes to GTID based promotions.

**Comment by rbroemeling** [comment]
@shlomi-noach That'll take a bit (it might be a few days), but yep I can do so. I'll get back to you when I have done so.

**Comment by americoru** [comment]
Hello!
I have some problem with making co master. I've go this topology:

```
dev-test3.vm:3306   [0s,ok,5.6.38-log,rw,MIXED,>>,GTID]
+ dev-test1.vm:3306 [0s,ok,5.6.38-log,ro,MIXED,>>,GTID]
+ dev-test2.vm:3306 [0s,ok,5.6.38-log,ro,MIXED,>>,GTID]
```

And when make co-master got this error:
```
# curl -s  "https://dev-test1.vm:3000/api/make-co-master/dev-test1.vm/3306" | jq '.'
{
  "Code": "ERROR",
  "Message": "Error 1776: Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active.",
  "Details": null
}
```

**Comment by shlomi-noach** [comment]
@americoru could you please open a new issue?

**Comment by americoru** [comment]
Ok, https://github.com/github/orchestrator/issues/566
