### ISSUE TITLE
Binlog servers (BLS) won't move between co-masters

### ISSUE THREAD

**Issue by ethan-riskiq** [openark/orchestrator#50]
My current replication topology is:

```
co-master A (writes)--->binlog01 --> slave A
|
|
co-master B (read-only) ---> binlog02 --> slave B
```

I have some maintenance I need to do on co-master A and want to point my binlog01 server to co-master B. When I try thru the UI it doesn't seem to work, doing it thru the cli gives me the following exception:

```
[root@inv1 orchestrator]#  ./orchestrator -c move-below -i binlog01.domain:3306 -d masterB.domain:3306 --noop
2017-01-13 14:42:51 ERROR Will not resolve empty hostname
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/outbrain/orchestrator/go/inst.(*Instance).MajorVersion(0xc2080c8000, 0x0, 0x0, 0x0)
	/home/snoach/dev/go/src/github.com/outbrain/orchestrator/go/inst/instance.go:282 +0xa2
github.com/outbrain/orchestrator/go/inst.(*Instance).IsSmallerMajorVersion(0xc2080c8000, 0xc2080c81c0, 0x82b9a0)
	/home/snoach/dev/go/src/github.com/outbrain/orchestrator/go/inst/instance.go:308 +0x28
github.com/outbrain/orchestrator/go/inst.(*Instance).CanReplicateFrom(0xc2080c8000, 0xc2080c81c0, 0x1, 0x0, 0x0)
	/home/snoach/dev/go/src/github.com/outbrain/orchestrator/go/inst/instance.go:437 +0x464
github.com/outbrain/orchestrator/go/inst.MoveBelow(0xc20801f8c0, 0xc20801eb80, 0x0, 0x0, 0x0)
	/home/snoach/dev/go/src/github.com/outbrain/orchestrator/go/inst/instance_topology.go:407 +0x47c
github.com/outbrain/orchestrator/go/app.Cli(0x7ffca576a686, 0xa, 0x0, 0x7ffca576a694, 0x18, 0x7ffca576a6b0, 0x10, 0xc20802af20, 0x4, 0x0, ...)
	/home/snoach/dev/go/src/github.com/outbrain/orchestrator/go/app/cli.go:175 +0x1e02
main.main()
	/home/snoach/dev/go/src/github.com/outbrain/orchestrator/go/cmd/orchestrator/main.go:646 +0xae4

goroutine 9 [select]:
github.com/pmylund/go-cache.(*janitor).Run(0xc20802b000, 0xc20803def0)
	/usr/share/golang/src/github.com/pmylund/go-cache/cache.go:946 +0x13f
created by github.com/pmylund/go-cache.runJanitor
	/usr/share/golang/src/github.com/pmylund/go-cache/cache.go:964 +0x8c

goroutine 7 [select]:
github.com/pmylund/go-cache.(*janitor).Run(0xc20802af60, 0xc20803dd70)
	/usr/share/golang/src/github.com/pmylund/go-cache/cache.go:946 +0x13f
created by github.com/pmylund/go-cache.runJanitor
	/usr/share/golang/src/github.com/pmylund/go-cache/cache.go:964 +0x8c

goroutine 8 [select]:
github.com/pmylund/go-cache.(*janitor).Run(0xc20802af70, 0xc20803ddd0)
	/usr/share/golang/src/github.com/pmylund/go-cache/cache.go:946 +0x13f
created by github.com/pmylund/go-cache.runJanitor
	/usr/share/golang/src/github.com/pmylund/go-cache/cache.go:964 +0x8c

goroutine 10 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 11 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208045b80)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 18 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20811c0a0)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 20 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20811c640)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c
```

is there something I'm missing here?

**Comment by shlomi-noach** [comment]
Is that a MaxScale binlog server?

A MaxScale binlog server cannot be moved. It just can't; you need to kill it, reconfigure it, then start it again.

This is known to `orchestrator` which is why the Web UI won't let you do it. I will need to add a similar check to the CLI to let you know this can't be done (and this will avoid the runtime error you got).

I'd argue you don't _want_ to move the binlog server, though. What you want to so is move `slave a`.
If using Pseudo-GTID, you can just 

```
orchestrator -c relocate -i slave.a -d binlog02
```

Actually this may just work without Pseudo-GTID for you, because of the relative simplicity of the topology (one up via binlog server). Anyway if it doesn't (could be), you'd use multiple steps:

```
orchestrator -c relocate -i slave.a -d binlog01
orchestrator -c move-below -i slave.a -d master.2
orchestrator -c relocate -i slave.a -d binlog02
```

**Comment by shlomi-noach** [comment]
My assignment: to make sure CLI refuses to move a BLS

**Comment by ethan-riskiq** [comment]
okay...any suggestions for how to do this without bringing down the write master and having to execute a change master on each binlog host while it's down?

**Comment by shlomi-noach** [comment]
> any suggestions for how to do this

Sorry, how to do _what_ ? 

The maintenance? Like I suggested, the binlog servers aren't your problem, are they? You wish to move the replicas around and I've given you the recipe to do that.

Otherwise I'm not sure what you are asking.

**Comment by shlomi-noach** [comment]
Closing this seeing this isn't an `orchestrator` issue. Feel free to continue discussion even as this issue is closed.
