### ISSUE TITLE
Orchestrator segfaulting on agent discovery.

### ISSUE THREAD

**Issue by cswingler** [openark/orchestrator#523]
I'm still trying to chase down the root cause of this issue, but I'm seeing Orchestrator segfault periodically on trying to discover against a MySQL instance with orchestrator-agent installed and running.

It seems to croak at least daily on us.

```
[martini] Completed 200 OK in 3.544196ms
[mysql] 2018/05/31 08:16:25 packets.go:36: unexpected EOF
[mysql] 2018/05/31 08:16:25 packets.go:36: unexpected EOF
2018-05-31 08:16:25 ERROR invalid connection
2018-05-31 08:16:25 ERROR ReadTopologyInstance(prod-mysql-infrastructure-useast1a-01:3306) show variables like 'maxscale%': invalid connection
[mysql] 2018/05/31 08:16:25 packets.go:36: unexpected EOF
[mysql] 2018/05/31 08:16:25 connection.go:372: invalid connection
[mysql] 2018/05/31 08:16:25 connection.go:372: invalid connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d473d]

goroutine 43943905 [running]:
github.com/github/orchestrator/go/agent.DiscoverAgentInstance(0xc422b54d06, 0x25, 0xbba, 0x111fd40, 0xc421bbe280)
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/agent/agent_dao.go:142 +0x33d
created by github.com/github/orchestrator/go/agent.SubmitAgent
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/agent/agent_dao.go:123 +0x20e

[martini] Completed 200 OK in 661.474µs
[mysql] 2018/05/29 18:16:25 packets.go:36: unexpected EOF
[mysql] 2018/05/29 18:16:25 packets.go:36: unexpected EOF
2018-05-29 18:16:25 ERROR invalid connection
2018-05-29 18:16:25 ERROR ReadTopologyInstance(prod-mysql-infrastructure-useast1a-01:3306) show variables like 'maxscale%': invalid connection
[mysql] 2018/05/29 18:16:25 packets.go:36: unexpected EOF
[mysql] 2018/05/29 18:16:25 connection.go:372: invalid connection
[mysql] 2018/05/29 18:16:25 connection.go:372: invalid connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d473d]

goroutine 2053620 [running]:
github.com/github/orchestrator/go/agent.DiscoverAgentInstance(0xc4219c2496, 0x25, 0xbba, 0x111fd40, 0xc4208528a0)
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/agent/agent_dao.go:142 +0x33d
created by github.com/github/orchestrator/go/agent.SubmitAgent
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/agent/agent_dao.go:123 +0x20e
2018-05-29 19:01:54 INFO starting orchestrator, version: 3.0.11, git commit: 351af88a4b6a449307fda2f669cbe7d8323b6dfd


[mysql] 2018/05/26 08:16:25 packets.go:36: unexpected EOF
[mysql] 2018/05/26 08:16:25 packets.go:36: unexpected EOF
2018-05-26 08:16:25 ERROR invalid connection
2018-05-26 08:16:25 ERROR ReadTopologyInstance(prod-mysql-infrastructure-useast1a-01:3306) show variables like 'maxscale%': invalid connection
[mysql] 2018/05/26 08:16:25 packets.go:36: unexpected EOF
[mysql] 2018/05/26 08:16:25 connection.go:372: invalid connection
[mysql] 2018/05/26 08:16:25 connection.go:372: invalid connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d473d]

goroutine 48432576 [running]:
github.com/github/orchestrator/go/agent.DiscoverAgentInstance(0xc422745066, 0x25, 0xbba, 0x111fd40, 0xc421eaad00)
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/agent/agent_dao.go:142 +0x33d
created by github.com/github/orchestrator/go/agent.SubmitAgent
        /home/shlomi-noach/go/src/github.com/github/orchestrator/go/agent/agent_dao.go:123 +0x20e
```

It's always against the same host from what I've seen, so there's very likely something misconfigured there, but that shouldn't be enough to cause Orchestrator to throw a `SIGSEGV.` :)

*note:* Nothing is actually being discovered here! The node referenced here itself is already in an Orchestrator cluster topology, it just seems to hit the code to refresh and discover it and gets confused.

Other notes: We upgraded directly from Orchestrator 3.0.2 to 3.0.11 via the debian package; and our agents are some release of 1.2.1. 

orchestrator config: https://gist.github.com/cswingler/5f79a00830b09fc1a205fc70346fe9d4
orchestrator-agent config: https://gist.github.com/cswingler/b769e4311bb1a0c35ca49fcb7a006d7e

**Comment by shlomi-noach** [comment]
@cswingler can you please try #526, it should fix the segfault (though I'm still unsure why discovery ended up the way it did)

**Comment by cswingler** [comment]
Thanks, I'll give that a whirl and report back.

**Comment by cswingler** [comment]
That fixed the segfault issue, thanks!

Log now reads:
```
[mysql] 2018/06/13 15:22:22 connection_go18.go:22: invalid connection
[mysql] 2018/06/13 15:22:22 packets.go:36: unexpected EOF
2018-06-13 15:22:22 ERROR invalid connection
2018-06-13 15:22:22 ERROR ReadTopologyInstance(prod-mysql-infrastructure-useast1a-01:3306) show variables like 'maxscale%': invalid connection
[mysql] 2018/06/13 15:22:22 connection.go:372: invalid connection
```

and carries on.

**Comment by shlomi-noach** [comment]
Can you please set `"SkipMaxScaleCheck": true` in your config file?
