### ISSUE TITLE
Integration test suite does not report failure to authenticate to orchestrator database

### ISSUE THREAD

**Issue by bbuchalter** [openark/orchestrator#609]
When [`tests/integration/test.sh` calls `deploy_internal_db()`](https://github.com/github/orchestrator/blob/master/tests/integration/test.sh#L139) it can execute as follows:
```
➜  orchestrator git:(master) ✗ /tmp/orchestrator-test --config=/tmp/orchestrator.conf.json --debug --stack -c redeploy-internal-db
2018-09-06 15:04:14 INFO starting orchestrator
2018-09-06 15:04:14 INFO Read config: /tmp/orchestrator.conf.json
2018-09-06 15:04:14 ERROR Error 1045: Access denied for user 'orc_server_user'@'172.21.0.1' (using password: YES)
goroutine 1 [running]:
runtime/debug.Stack(0x71, 0x60, 0xc4202ae240)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/github/orchestrator/vendor/github.com/openark/golib/log.logErrorEntry(0x2, 0x486c620, 0xc42000c140, 0x486c620, 0xc42000c140)
        /Users/brianb/src/github.com/github/orchestrator/vendor/github.com/openark/golib/log/log.go:178 +0xe9
github.com/github/orchestrator/vendor/github.com/openark/golib/log.Errore(0x486c620, 0xc42000c140, 0x2a, 0x0)
        /Users/brianb/src/github.com/github/orchestrator/vendor/github.com/openark/golib/log/log.go:224 +0x3e
github.com/github/orchestrator/go/db.OpenOrchestrator(0xc4202c6000, 0x137, 0xc4202c6000)
        /Users/brianb/src/github.com/github/orchestrator/go/db/db.go:144 +0x81f
github.com/github/orchestrator/go/db.QueryOrchestrator(0xc4202c6000, 0x137, 0x0, 0x0, 0x0, 0xc42029b608, 0x137, 0xc4201fe0e0)
        /Users/brianb/src/github.com/github/orchestrator/go/db/db.go:359 +0x131
github.com/github/orchestrator/go/inst.ReadClustersInfo(0x0, 0x0, 0x1800, 0x1800, 0x4738e80, 0xc4201ea001, 0x100c4201ea020)
        /Users/brianb/src/github.com/github/orchestrator/go/inst/instance_dao.go:1914 +0x182
github.com/github/orchestrator/go/inst.ReadClusters(0x7ffeefbffa2f, 0x47b5525, 0x14, 0x1, 0x4b78140)
        /Users/brianb/src/github.com/github/orchestrator/go/inst/instance_dao.go:1868 +0x3e
github.com/github/orchestrator/go/app.Cli(0x7ffeefbffa2f, 0x14, 0x0, 0x47a6be0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/brianb/src/github.com/github/orchestrator/go/app/cli.go:1578 +0x9e42
github.com/github/orchestrator/go/app.CliWrapper(0x7ffeefbffa2f, 0x14, 0xc4200e0000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/brianb/src/github.com/github/orchestrator/go/app/cli.go:149 +0x20d
main.main()
        /Users/brianb/src/github.com/github/orchestrator/go/cmd/orchestrator/main.go:158 +0xd13
Redeployed internal db
➜  orchestrator git:(master) ✗ echo $?
0
```

This exit code of zero is because `OpenOrchestrator` calls `Errore` instead of `Fatale` [when it encounters an error setting up the database for the first time](https://github.com/github/orchestrator/blob/master/go/db/db.go#L144). 

But we [depend on a non-zero exit code](https://github.com/github/orchestrator/blob/master/tests/integration/test.sh#L150) to know if there's been a failure setting up the database.

Remedies include:
* Changing how we detect a failure in the integration test setup
* Call `Fatale` when the database can't be setup correctly the first time

Please advise on how you'd like me to remedy. Happy to PR. 👍

**Comment by shlomi-noach** [comment]
Permalink for first database access: https://github.com/github/orchestrator/blob/33254f07614fdf4eb4e36337abc849797d23ae41/go/db/db.go#L144

Thank you. I agree that the above should be `Fatale`. PR is most welcome!

**Comment by bbuchalter** [comment]
I'm going to approach this differently than I did in #618 by changing how the command is invoked here: https://github.com/github/orchestrator/blob/49eab6d8be3942c6f10cf3604a0bc3af83ef7bae/go/app/cli.go#L1575

I'll catch the error and then call `log.Fatale(err)`, so we get the desired exit code.
