### ISSUE TITLE
Get the panic when failover by force_master_takeover

### ISSUE THREAD

**Issue by wufeirong** [openark/orchestrator#902]
```2019-05-29 22:14:58 DEBUG orchestrator/raft: applying command 337720: write-recovery-step
[mysql] 2019/05/29 22:14:59 packets.go:36: unexpected EOF
2019-05-29 22:14:59 INFO topology_recovery: Writing KV [mysql/master/04582a54-821c-11e9-843b-fa163e45fd37:10.226.1.239:3306 mysql/master/04582a54-821c-11e9-843b-fa163e45fd37/hostname:10.226.1.239 mysql/master/04582a54-821c-11e9-843b-fa163e45fd37/port:3306 mysql/master/04582a54-821c-11e9-843b-fa163e45fd37/ipv4:10.226.1.239 mysql/master/04582a54-821c-11e9-843b-fa163e45fd37/ipv6:]
[mysql] 2019/05/29 22:14:59 packets.go:36: unexpected EOF
2019-05-29 22:14:59 ERROR invalid connection
2019-05-29 22:14:59 ERROR ReadTopologyInstance(10.224.131.206:3306) show variables like 'maxscale%': invalid connection
[mysql] 2019/05/29 22:14:59 packets.go:36: unexpected EOF
[mysql] 2019/05/29 22:14:59 connection.go:372: invalid connection
[mysql] 2019/05/29 22:14:59 connection.go:372: invalid connection
2019-05-29 22:14:59 DEBUG orchestrator/raft: applying command 337721: write-recovery-step
2019-05-29 22:14:59 DEBUG orchestrator/raft: applying command 337722: put-key-value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x27b pc=0x88782f]

goroutine 56269304 [running]:
github.com/github/orchestrator/go/inst.SetReadOnly(0xc42597e6c0, 0x1, 0x0, 0x0, 0x43b828)
	/home/shlomi-noach/go/src/github.com/github/orchestrator/go/inst/instance_topology_dao.go:992 +0x6f
github.com/github/orchestrator/go/logic.checkAndRecoverDeadMaster.func1(0xc42597e6c0, 0xc421d84700)
	/home/shlomi-noach/go/src/github.com/github/orchestrator/go/logic/topology_recovery.go:844 +0x34
created by github.com/github/orchestrator/go/logic.checkAndRecoverDeadMaster
	/home/shlomi-noach/go/src/github.com/github/orchestrator/go/logic/topology_recovery.go:843 +0x638
```

**Comment by shlomi-noach** [comment]
Thank you. I actually believe this is fixed since a few days ago from `master`. If you'd like to pull `master` and build, please do. Otherwise I may make a release next week.
